spring:
  application:
   name: dvd-shelf
  datasource:
   url: jdbc:mysql://localhost:3306/dvd_shelf?createDatabaseIfNotExist=true
   username: root
   password: "@Development789"
  
logging:
  level:
    com.gcu.dvdshelf: DEBUG